#!/usr/bin/env node

// not sure why I have the self signed cert issue
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const io = require('socket.io-client');
const port = process.env.PORT || 3000;
const socket = io('https://web-hook-bin.herokuapp.com');
const request = require('request');

const bucketName = process.argv[2];
const forwardingUrl = process.argv[3];

if (!bucketName || !forwardingUrl) {
  console.log();
  console.log('incorrect usage, params are: <bucketName> <forwardingUrl>');
  console.log();
  process.exit(1);
}

socket.on('webhook', (webhook) => {
  if (bucketName === webhook.bucket) {
    console.log(`${new Date()} - Received webhook from ${bucketName}`);
    const reqObj = {
      url: forwardingUrl,
      body: webhook.body,
      json: true,
    };

    if (webhook.headers && webhook.headers.authorization) {
      reqObj.headers = { authorization: webhook.headers.authorization };
    }

    request.post(reqObj, function (err, response, body) {
      if (err) {
        console.log(err);
        process.exit(1);
      }
      console.log(`${new Date()} - Successfully forwarded webhook to ${forwardingUrl}`);
    });
  }
});
