#!/usr/bin/env node

require('dotenv').config();

const promptly = require('promptly');
const { resetBin } = require('../dist/actions');

const REMOTE_REQUEST_BIN_URL = process.env.REMOTE_REQUEST_BIN_URL;
if (!REMOTE_REQUEST_BIN_URL) {
  throw new Error('REMOTE_REQUEST_BIN_URL is required');
}

const REMOTE_REQUEST_BIN_PASSWORD = process.env.REMOTE_REQUEST_BIN_PASSWORD;

async function main() {
  let password = REMOTE_REQUEST_BIN_PASSWORD || '';
  if (!REMOTE_REQUEST_BIN_PASSWORD || REMOTE_REQUEST_BIN_PASSWORD === '') {
    password = await promptly.password('Reset password: ');
  }
  const data = await resetBin(REMOTE_REQUEST_BIN_URL, password);
  return data;
}

main()
  .then((data) => console.log(data))
  .catch((err) => console.error(err));
